name: 'Contrast Scan Analyze'
description: 'Perform SAST analysis of a project'
inputs:
  apiKey:
    description: 'An agent API key provided by Contrast (required).'
    required: true
  authHeader:
    description: 'User authorization credentials provided by Contrast (required).'
    required: true
  orgId:
    description: 'The ID of your organization in Contrast (required).'
    required: true
  apiUrl:
    description: 'The name of the host. Includes the protocol section of the URL (https://). Defaults to https://ce.contrastsecurity.com. (optional)'
    required: false
    default: "https://ce.contrastsecurity.com"
  artifact:
    description: 'The Artifact to Scan on the Contrast Platform.'
    required: true
  projectName:
    description: 'The name of the project you want to scan in Contrast.'
    required: false
  projectId:
    description: 'The ID of your project in Contrast.'
    required: false
  language:
    description: 'The language of your project.'
    required: false
  timeout:
    description: 'Set a specific time span (in seconds) before the function times out. The default timeout is 5 minutes if timeout is not set.'
    required: false
    default: 300
  severity:
    description: 'Allows user to report vulnerabilities above a chosen severity level. Values for level are high, medium or low. (Note: Use this input in combination with the fail input, otherwise the action will exit)'
    required: false
  fail:
    description: 'When set to true, fails the action if CVEs have been detected that match at least the severity option specified.'
    required: false
  debug:
    description: 'When set to true, enables verbose/debug output.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
