name: 'Contrast Scan Analyze'
description: 'Perform SAST analysis of a project'
inputs:
  apiKey:
    description: 'An agent API key provided by Contrast (required).'
    required: true
  orgId:
    description: 'The ID of your organization in Contrast (required).'
    required: true
  apiUrl:
    description: 'The name of the host and, optionally, the port expressed as <host>:<port>. Does not include the protocol section of the URL (https://). Defaults to ce.contrastsecurity.com. (optional)'
    required: false
    default: "ce.contrastsecurity.com"
  authHeader:
    description: 'User authorization credentials provided by Contrast (required).'
    required: true
  projectName:
    description: 'The name of the project you want to scan in Contrast (required).'
    required: true
  artifact:
    description: 'The Artifact to Scan on the Contrast Platform.'
    required: true
  language:
    description: 'The language of the project you want to scan (required).'
    required: false
  timeout:
    description: 'Set a specific time span (in seconds) before the function times out. The default timeout is 5 minutes if timeout is not set.'
    required: false
  sarif:
    description: 'The path in which to save the SARIF results.'
    required: false
    default: "results.json"
  waitForScan:
    description: 'Wait for the scan to complete before continuing'
    required: false
    default: 'true'
  saveScanResults:
    description: 'After the scan has completed successfully, store the scan results in SARIF format to disk.'
    required: false
    default: 'true'
runs:
  using: 'docker'
  image: 'Dockerfile'
