name: Contrast Scan Action Regression
on:
  pull_request:
jobs:
  trigger_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Tests and Wait
        uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: Contrast-Security-Inc
          repo: sast-e2e
          github_token: ${{ secrets.SCAN_PAT }}
          ref: master
          inputs: '"trigger_repo_url": "${{ github.event.repository.html_url }}","trigger_commit_url": "${{ github.event.head_commit.url }}","trigger_user_email": "${{ github.event.head_commit.author.email }}"}'
          workflow_file_name: dev-test.yml
          wait_interval: 10
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true