name: create-release


on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
    types:
      - closed


permissions:
  contents: write
jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675 # v2.3.3
        with:
          fetch-depth: 0

      - name: Git Version
        id: version
        uses: codacy/git-version@80c816f11db8dea5e3a81025f598193015b51832
        with:
          release-branch: main
          prefix: v

      - name: Create Release
        uses: step-security/action-gh-release@dc29ef0d1f6f9a032a97ec797d9cb7ea788dde41 # v2.6.1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          token: ${{secrets.SCA_OSS_PAT}} # Used so pipeline gets triggered from this one
          # See https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow