name: create-release


on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
    types:
      - closed


permissions:
  contents: write
jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0

      - name: Git Version
        id: version
        uses: codacy/git-version@80c816f11db8dea5e3a81025f598193015b51832
        with:
          release-branch: main
          prefix: v

      - name: Create Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        with:
          tag_name: ${{ steps.version.outputs.version }}
          token: ${{secrets.SCA_OSS_PAT}} # Used so pipeline gets triggered from this one
          # See https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow