name: Keep the versions up-to-date

on:
  release:
    types: [published, edited]

permissions:
  contents: write
jobs:
  actions-tagger:
    runs-on: "ubuntu-latest"
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - uses: Actions-R-Us/actions-tagger@330ddfac760021349fef7ff62b372f2f691c20fb
        with:
          publish_latest_tag: false